server:
  port: ${PORT:8080}
  origin: ${ORIGIN:*}
spring:
  application:
    name: challenge-full-stack-game
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://sofka:sofka@sofka.58bqo.mongodb.net/game?authSource=admin&compressors=zlib&retryWrites=true&w=majority&ssl=true}
  rabbitmq:
    #addresses: ${BUS_URI:amqps://qqtbnckp:uRNluVYL_k1lp_B9HfY966hbnqgCKi2B@jackal.rmq.cloudamqp.com/qqtbnckp}
    uri: ${BUS_URI:amqp://guest:guest@localhost:5672}
